import fs from 'fs';
import path from 'path';
import { MeshData } from './meshExporter';

/**
 * Exports mesh to OBJ file with vertex colors.
 * Uses extended OBJ format: v x y z r g b
 * This is not part of the official OBJ spec but is widely supported by Blender and other 3D rendering tools.
 */
export class ObjExporter {
  /**
   * Export mesh to OBJ format with extended vertex colors
   */
  static async exportObj(meshData: MeshData, outputDir: string): Promise<void> {
    try {
      const outputPath = path.join(outputDir, `mesh.obj`);
      const metadata = {
        vertexCount: meshData.metadata.vertexCount,
        faceCount: meshData.metadata.triangleCount,
      };

      await this.writeExtendedObj(outputPath, meshData.positions, meshData.colors, metadata);
    } catch (e: any) {
      console.error('OBJ export failed:', e.message);
    }
  }

  /**
   * Write OBJ file with format: v x y z r g b
   */
  private static async writeExtendedObj(
    filepath: string,
    positions: Float32Array,
    colors: Float32Array,
    metadata: { vertexCount: number; faceCount: number },
  ): Promise<void> {
    const { vertexCount, faceCount } = metadata;

    const writeStream = fs.createWriteStream(filepath, { encoding: 'ascii' });

    // Write header
    writeStream.write('# File generated by simshady export - https://github.com/open-pv/simshady\n');
    writeStream.write('# Extended OBJ format with per-vertex colors: v x y z r g b\n');
    writeStream.write('\n');

    // Write vertices with colors
    for (let i = 0; i < vertexCount; i++) {
      const posIdx = i * 3;
      const colorIdx = i * 3;

      const x = positions[posIdx].toFixed(6);
      const y = positions[posIdx + 1].toFixed(6);
      const z = positions[posIdx + 2].toFixed(6);

      const r = colors[colorIdx].toFixed(6);
      const g = colors[colorIdx + 1].toFixed(6);
      const b = colors[colorIdx + 2].toFixed(6);

      writeStream.write(`v ${x} ${y} ${z} ${r} ${g} ${b}\n`);
    }

    writeStream.write('\n');

    // Write faces
    for (let i = 0; i < faceCount; i++) {
      const v0 = i * 3 + 1;
      const v1 = i * 3 + 2;
      const v2 = i * 3 + 3;
      writeStream.write(`f ${v0} ${v1} ${v2}\n`);
    }

    // Close stream
    await new Promise<void>((resolve, reject) => {
      writeStream.on('finish', resolve);
      writeStream.on('error', reject);
      writeStream.end();
    });
  }
}
