name: Publish Package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v7
        with:
          node-version: '26.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@openpv'
      - run: npm install
      - run: npm run build
      - name: Update npm # Seems like trusted publishing only works with npm
        run: npm install -g npm@latest
      - run: npm publish
